Fix: Cannot process multiple parallel `takePicture`. Need to wait for on request to finish first. (#97)
Prev to this change, Samsung Galaxy S4 crashes in demo app due to this error:
```
[CAM-BACK]-ERR(virtual android::status_t android::ExynosCameraHWImpl::takePicture()):capture already in progress
java.lang.RuntimeException: takePicture failed
  at android.hardware.Camera.native_takePicture(Native Method)
  at android.hardware.Camera.takePicture(Camera.java:1338)
  at com.google.android.cameraview.Camera1.takePictureInternal(Unknown Source)
  at com.google.android.cameraview.Camera1$2.onAutoFocus(Unknown Source)
```